### ISSUE TITLE
Check features length before calling `choice` in KID

### ISSUE THREAD

**Issue by toshas** [toshas/torch-fidelity#8]
```python
Traceback (most recent call last):
  File "/cluster/home/alugmayr/.local/bin/fidelity", line 8, in <module>
    sys.exit(main())
  File "/cluster/home/alugmayr/.local/lib/python3.8/site-packages/torch_fidelity/fidelity.py", line 98, in main
    metrics = calculate_metrics(args.input1, input_2=args.input2, **vars(args))
  File "/cluster/home/alugmayr/.local/lib/python3.8/site-packages/torch_fidelity/metrics.py", line 145, in calculate_metrics
    metric_kid = kid_featuresdict_to_metric(featuresdict_1, featuresdict_2, feature_layer_kid, **kwargs)
  File "/cluster/home/alugmayr/.local/lib/python3.8/site-packages/torch_fidelity/metric_kid.py", line 113, in kid_featuresdict_to_metric
    metric = kid_features_to_metric(features_1, features_2, **kwargs)
  File "/cluster/home/alugmayr/.local/lib/python3.8/site-packages/torch_fidelity/metric_kid.py", line 91, in kid_features_to_metric
    f1 = features_1[rng.choice(len(features_1), kid_subset_size, replace=False)]
  File "mtrand.pyx", line 954, in numpy.random.mtrand.RandomState.choice
ValueError: Cannot take a larger sample than population when 'replace=False'
```

**Comment by Peter-Teng** [comment]
I have met this problem. How can I solve it?

**Comment by toshas** [comment]
This is going to be fixed in the next version: https://github.com/toshas/torch-fidelity/pull/2/files#diff-648d3fdbc21590d005c274947dc7674c545352a273cc29dfc03d7571e17ad56aR81-R86
An immediate fix is available in the `wip` branch.
